name: Build Release APK manually 

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'select build flavor'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      build_type:
        description: 'Build Type:'
        required: true
        default: 'release'
        options:
          - release
          - debug
jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter 
        uses: subosito/flutter-action@v2
        with: 
          channel: 'stable'
          cache: true
      - name: Get Flutter dependencies 
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format --set-exit-if-changed lib

      - name: Static Analysis
        run: flutter analyze lib
      
      - name: Run Tests
        run: flutter test

      - name: Build Apk
        run: |
          flutter build apk --${{ inputs.build_type }} \
            --flavor ${{ inputs.flavor }} \
            --target lib/main_${{ inputs.flavor }}.dart \
            --no-color
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.flavor}}-${inputs.build_type}-apk
          path: build/app/outputs/flutter-apk/${{ inputs.build_type }}app-${{inputs.flavor}}-${{inputs.build_type}}.apk
          retention-days: 4